#!/usr/bin/env python

##
## Unpack a table-of-contents file
##

import os, sys, re

if len(sys.argv) < 2:
    fp = sys.stdin
    if sys.stdin.isatty():
        print >> sys.stderr, "[reading from standard input]"
else:
    fp = file(sys.argv[1], 'rb')

chk = fp.read(3)
if chk <> 'XM2':
    print >> sys.stderr, "Input is not in the correct format."
    sys.exit(1)

data = {}
num_read = 0
while True:
    flen = ord(fp.read(1)) ; num_read += 1
    if flen == 255:
        break
    
    fname = fp.read(flen)  ; num_read += len(fname)
    print >> sys.stderr, "File name (length %d): %s" % (flen, fname)
    
    keys = []
    nkeys = ord(fp.read(1)) ; num_read += 1
    for pos in range(nkeys):
        klen = ord(fp.read(1)) ; num_read += 1
        keys.append(fp.read(klen)) ; num_read += klen
    
    data[fname] = keys
    if fp.read(1) <> '\xff':
        print >> sys.stderr, \
              "Warning:  Missing record terminator at position %d." % \
              num_read
    
    num_read += 1

keys = data.keys()
keys.sort()
for k in keys:
    print "%s:%s" % (k, str.join(',', data[k]))

fp.close()

# Here there be dragons
    
    
